#version: '3.8'

services:

  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qazwsx}
      POSTGRES_DB: ${POSTGRES_DB:-project_db}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
        
